<?php

$config = array(
  'admin' => array(
    'core:AdminPassword',
  ),
  'diagnostics-sp' => array(
    'exampleauth:UserPass',
    'nexiadealer:nexiadealer' => array(
      'GUID' => '51e97951-0cbb-4c85-ae1e-dc5f3460edce',
      'UserID' => 'NexiaDealer',
      'userFullName' => 'Christina Cho',
      'userFirstName' => 'Christina',
      'userLastName' => 'Cho',
      'userEmail' => "ccho@irco.com",
      'userPermissions' => 'Brand.Trane,Channel.IWD,Account.Dealer,Nexia.Dealer',
      'companyId' => '47ee0922-5989-4e41-9e99-d23c11fa9f5b',
      'companyName' => 'Demo IWD Customer',
      'companyPhoneNumber' => '412-293-1212',
      'companyContactEmail' => '',
      'companyAddress' => '370 Interlocken Blvd',
      'companyCity' => 'Broomfield',
      'companyState' => 'CO',
      'companyZip' => '80020',
      'companyBrand' => 'Nexia',
      'companyChannel' => '',
      'companyLogo' => ''
    ),
    'nexiaadmin:nexiaadmin' => array(
      'GUID' => '62e306e5-4597-493a-8271-dd2c3c546b19',
      'UserID' => 'NexiaAdmin',
      'userFullName' => 'Franklin Fogherty',
      'userFirstName' => 'Franklin',
      'userLastName' => 'Fogherty',
      'userPermissions' => 'Brand.Trane,Channel.IWD,Account.Dealer,Nexia.Admin',
      'companyId' => '47ee0922-5989-4e41-9e99-d23c11fa9f5b',
      'companyName' => 'Nexiatest Dealer Test',
      'companyPhoneNumber' => '412-293-1212',
      'companyContactEmail' => '',
      'companyAddress' => '370 Interlocken Blvd',
      'companyCity' => 'Broomfield',
      'companyState' => 'CO',
      'companyZip' => '80020',
      'companyBrand' => 'Nexia',
      'companyChannel' => '',
      'companyLogo' => ''
    ),
    'nexiafsr:nexiafsr' => array(
      'GUID' => '62e306e5-4597-493a-8271-dd2c3c546b19',
      'UserID' => 'nexiafsr',
      'userFullName' => 'Franklin Fogherty',
      'userFirstName' => 'Franklin',
      'userLastName' => 'Fogherty',
      'userPermissions' => 'Brand.Trane,Channel.IWD,Account.OfficeSupplier,Nexia.FSR,Nexia.Dealer',
      'companyId' => 'feba2f1e-5f63-42f9-be20-c0bc66b6ec9a',
      'companyName' => 'Demo IWD',
      'companyPhoneNumber' => '412-293-1212',
      'companyContactEmail' => '',
      'companyAddress' => '1234 Test street',
      'companyCity' => 'Nashville',
      'companyState' => 'TN',
      'companyZip' => '12345',
      'companyBrand' => 'Trane',
      'companyChannel' => 'IWD',
      'companyLogo' => 'https://staging.comfortsite.com/Resources/Partners/FEBA2F1E-5F63-42F9-BE20-C0BC66B6EC9A/logos/sampledistributorlogosm.jpg'
    ),
  ),
);
