---
name: Docker build and publish (main)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ghcr.io/kuisathaverat/docker-test-saml-idp
      VERSION: "1.16.0"
      SIMPLESAMLPHP_VERSION: "1.15.2"
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build --build-arg SIMPLESAMLPHP_VERSION=${{ env.SIMPLESAMLPHP_VERSION }} -t "${{ env.REPOSITORY }}:${{ env.VERSION }}" .
          docker push "${{ env.REPOSITORY }}:${{ env.VERSION }}"