name: Release Drafter

on:
    push:
        tags:
            - "*.*.*"
    release:
        types:
            - created
            - published

permissions:
    contents: read

jobs:
    update_release_draft:
        permissions:
            # write permission is required to create a github release
            contents: write
            # write permission is required for autolabeler
            # otherwise, read permission is required at least
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: version
              id: version
              run: |
                  tag=${GITHUB_REF/refs\/tags\//}
                  version=${tag#v}
                  echo "version=${version}" >> $GITHUB_OUTPUT
            - uses: release-drafter/release-drafter@v5
              with:
                  version: ${{ steps.version.outputs.version }}
                  publish: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
